  version: '3.8' # https://docs.docker.com/compose/compose-file/compose-versioning/
  services:
    storage:
      image: nhost/hasura-storage:0.3.6 # https://hub.docker.com/r/nhost/hasura-storage/tags
      restart: unless-stopped
      ports:
        - '8000:8000'
      environment:
        DEBUG: "true"
        DATABASE_URL: ${DATABASE_URL}
        S3_ACCESS_KEY: ${S3_ACCESS_KEY}
        S3_SECRET_KEY: ${S3_SECRET_KEY}
        S3_ENDPOINT: ${S3_ENDPOINT}
        S3_BUCKET: "default"
        GRAPHQL_ENGINE_BASE_URL: ${GRAPHQL_ENGINE_BASE_URL}
        GRAPHQL_ENDPOINT: ${GRAPHQL_ENDPOINT}
        HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
        # JWT_SECRET: ${JWT_SECRET}
        # KEY: ${KEY}
      command: serve
