version: 3
endpoint: https://api.yourdomain.com/v1/graphql
admin_secret: <your-admin-secret>
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
