#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
package_update: true
package_upgrade: true
runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh
  - sudo usermod -aG docker $USER
  - sudo apt-get update
  - sudo apt-get upgrade -y